### ISSUE TITLE
Strange behavior with multi-carets

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_bootstrap_complete#21]
![Peek 26-09-2021 21-21](https://user-images.githubusercontent.com/25956396/135014002-f2ca6700-47cb-41ff-bde5-fca42a811e5e.gif)

1º Cancel carets
2º Delete begin quotes

**Comment by Alexey-T** [comment]
I see some problem here because plugin activates on multi-carets. IMO it should not. 

And this is a bug:

after this text and carets:

![Screenshot from 2021-09-28 13-35-43](https://user-images.githubusercontent.com/4154978/135071634-a2714b87-a7f2-405b-8f53-4369490a1d69.png)

plugin CAN be activated and it gives BROKEN text (after choosing text "badge")
![Screenshot from 2021-09-28 13-35-46](https://user-images.githubusercontent.com/4154978/135071714-0c0381db-c90c-44ce-8909-2b72a5b1f72c.png)

**Comment by Alexey-T** [comment]
@halfbrained

**Comment by eltonfabricio10** [comment]
Fixed! :)

**Comment by Alexey-T** [comment]
Pls re-open the issue-- we have the clear BUG which I shown on screenshots.
